# Generated by Django 5.1.3 on 2025-01-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='number_of_members',
            field=models.IntegerField(default=0),
        ),
    ]
