# Generated by Django 5.1.5 on 2025-02-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_society_number_of_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='building',
            field=models.CharField(default='Default Building', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='flat_number',
            field=models.CharField(default='001', max_length=10),
        ),
    ]
