# Generated by Django 5.1.5 on 2025-02-02 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_member_building_member_flat_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='building',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='flat_number',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.member')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.society')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
