# Generated by Django 5.1.5 on 2025-02-02 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_member_building_alter_member_flat_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Announcement', 'verbose_name_plural': 'Announcements'},
        ),
        migrations.AlterModelOptions(
            name='society',
            options={'ordering': ['name'], 'verbose_name_plural': 'Societies'},
        ),
    ]
