# Generated by Django 5.1.5 on 2025-02-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
