# Generated by Django 5.1.5 on 2025-02-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_billtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='billtype',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='bill_qr_codes/'),
        ),
    ]
