# Generated by Django 5.1.6 on 2025-02-23 12:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_billtype_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='billtype',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
