# Generated by Django 5.1.6 on 2025-02-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_billtype_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='billtype',
            name='status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending')], default='PENDING', max_length=20),
            preserve_default=False,
        ),
    ]
