# Generated by Django 5.1.6 on 2025-02-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_billtype_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billtype',
            options={},
        ),
        migrations.AlterField(
            model_name='billtype',
            name='due_date',
            field=models.DateField(),
        ),
    ]
